FROM --platform=linux/amd64 python:3.11

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

# Copy the modified dependency file to fix the langchain module
COPY modifications/openai.py /usr/local/lib/python3.11/site-packages/langchain_community/embeddings/openai.py

EXPOSE 80

ENV FORWARDED_ALLOW_IPS "*"

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80", "--forwarded-allow-ips", "*", "--proxy-headers"]
